server:
  #端口号
  port: 9031
  servlet:
    context-path: /cache

spring:
  application:
    name: inter-hsp-cache


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka/
      
  instance:
    prefer-ip-address: true
    #      http://localhost:9092/eureka/
#开启熔断
#feign:
#  hystrix:
#    enabled: true

sidecar:
  port: 9990     #cache异构微服务的端口
  healthUri: http://10.10.10.250:9990/V1/api/testConnect  #对应第三方程序的health接口
