server:
  #端口号
  port: 9033
  servlet:
    context-path: /doctor
##数据库连接信息
spring:
  application:
    name: inter-hsp-doctor
  redis:
    host: 10.10.10.100
    port: 6379
    timeout: 20000
    #    集群环境打开下面注释，单机不需要打开
    #    cluster:
    #      集群信息
    #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
    #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
    #      maxRedirects: 3
#    pool:
#      min-idle: 1
#      max-totle: 1000
#      max-wait: -1
#      max-idle: 100
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

#http client配置服务
http:
  #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
#用户下最多绑定的就诊人数量
params:
  bindPatients: 10

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
      #      http://localhost:9092/eureka/
      #开启熔断
feign:
  hystrix:
    enabled: true

sidecar:
  port: 9037     #异构微服务的端口
  healthUri: http://localhost:9037/demo/demo  #对应第三方程序的health接口
