server:
  #端口号
  port: 9034
  servlet:
    context-path: /feign
spring:
  application:
    name: inter-hsp-feign
  main:
    allow-bean-definition-overriding: true  
eureka:
  instance:
    prefer-ip-address: true
         #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
#      http://localhost:9092/eureka/
 
## 这个要有，如果不加，只加了上面也没用
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: false