server:
  #端口号
  port: 9035
  #servlet:
 #  context-path: /file

spring:
  application:
    name: inter-hsp-file


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka/
  instance:
    prefer-ip-address: true
    hostname: 10.10.10.250
     #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
    #      http://localhost:9092/eureka/
#开启熔断
#feign:
#  hystrix:
#    enabled: true

sidecar:
  port: 9991     #文件服务异构微服务的端口
  healthUri: http://${eureka.instance.hostname}:${sidecar.port}/V1/api/test  #对应第三方程序的health接口
