server:
  port: 9049
  servlet:
    context-path: /Oauth
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://10.10.10.100:3307/internethsp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
logging:
  level:
    org:
      springframework:
        security:
          oauth2: debug
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
#      http://localhost:9092/eureka/
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true         
          